version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-app .
      - docker tag my-app:latest <account-id>.dkr.ecr.<region>.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push <account-id>.dkr.ecr.<region>.amazonaws.com/my-app:latest

artifacts:
  files: "**/*"
